### ISSUE TITLE
Multiple http connections could crash daemon

### ISSUE THREAD

**Issue by aguycalled** [NAVCoin/navtech#5]
data:    dist/navtech.js:24595 - _http_outgoing.js:356
data:    dist/navtech.js:24595 -     throw new Error('Can\'t set headers after they are sent.');
data:    dist/navtech.js:24595 -     ^
data:    dist/navtech.js:24595 - Error: Can't set headers after they are sent.
data:    dist/navtech.js:24595 -     at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
data:    dist/navtech.js:24595 -     at ServerResponse.header (/root/navtech/node_modules/express/lib/response.js:719:10)
data:    dist/navtech.js:24595 -     at ServerResponse.send (/root/navtech/node_modules/express/lib/response.js:164:12)
data:    dist/navtech.js:24595 -     at Object.O.w.returnCheckedNode (/root/navtech/dist/navtech.js:1:10651)
data:    dist/navtech.js:24595 -     at /root/navtech/dist/navtech.js:1:10230
data:    dist/navtech.js:24595 -     at Hash.<anonymous> (/root/navtech/node_modules/md5-file/index.js:38:5)
data:    dist/navtech.js:24595 -     at Hash.g (events.js:291:16)
data:    dist/navtech.js:24595 -     at emitNone (events.js:86:13)
data:    dist/navtech.js:24595 -     at Hash.emit (events.js:185:7)
data:    dist/navtech.js:24595 -     at emitReadable_ (_stream_readable.js:432:10)
data:    dist/navtech.js:24595 -     at emitReadable (_stream_readable.js:426:7)
data:    dist/navtech.js:24595 -     at readableAddChunk (_stream_readable.js:187:13)
data:    dist/navtech.js:24595 -     at Hash.Readable.push (_stream_readable.js:134:10)
data:    dist/navtech.js:24595 -     at Hash.Transform.push (_stream_transform.js:128:32)
data:    dist/navtech.js:24595 -     at Hash._flush (crypto.js:68:8)
data:    dist/navtech.js:24595 -     at Hash.<anonymous> (_stream_transform.js:118:12)

[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2017-11-23T18:54:26+13:00","ped":"2017-11-23T21:30:58+13:00"})

**Comment by mogrith** [comment]
I'm seeing same issue
